polyexam2: poly2.o
	g++ -o polyexam2 polyexam2.cxx poly2.o 

polytest2: poly2.o
	g++ -o polytest2 polytest2.cxx poly2.o

poly2.o: poly2.cpp
	g++ poly2.cpp -c


clean:
	rm -f polytest2 polyexam2 poly2.o
